# How to use this file:
# Do not add PATHs here, add them to ~/.shell_paths or ~/.shell_paths_local
# Do not add local machine specific configuration here, add it to ~/.zshrc_local

# Set up PATH
if [ -r ~/.shell_paths ]; then
    . ~/.shell_paths
fi

# Set up the prompt
if [ -r ~/.powerline/powerline/bindings/zsh/powerline.zsh ]; then
	source  ~/.powerline/powerline/bindings/zsh/powerline.zsh
fi

setopt histignorealldups sharehistory

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Prefer vim for everything
# editor
export EDITOR=vi
# command prompt
bindkey -v

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolorsrc && eval "$(dircolors -b ~/.dircolorsrc)" || eval "$(dircolors -b)"
fi

if [ -r ~/.shell_aliases ]; then
    . ~/.shell_aliases
fi

if [ -f ~/.asdf/asdf.sh ]; then
  . ~/.asdf/asdf.sh
fi

if [ -r ~/.zshrc_local ]; then
    . ~/.zshrc_local
fi
